export const USER_LOGIN_REQUESTED = 'USER_LOGIN_REQUESTED';
export const USER_LOGIN_SUCCEEDED = 'USER_LOGIN_SUCCEEDED';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET = 'USER_SET';

export const APPS_FETCH_REQUESTED = 'APPS_FETCH_REQUESTED';
export const APPS_FETCH_SUCCEEDED = 'APPS_FETCH_SUCCEEDED';
export const APPS_FETCH_FAILED = 'APPS_FETCH_FAILED';

export const APP_USERS_FETCH_REQUESTED = 'APP_USERS_FETCH_REQUESTED';
export const APP_USERS_FETCH_SUCCEEDED = 'APP_USERS_FETCH_SUCCEEDED';
export const APP_USERS_FETCH_FAILED = 'APP_USERS_FETCH_FAILED';

export const APP_UPDATE_TOGGLE = 'APP_UPDATE_TOGGLE';
export const APP_UPDATE_REQUESTED = 'APP_UPDATE_REQUESTED';
export const APP_UPDATE_SUCCEEDED = 'APP_UPDATE_SUCCEEDED';
export const APP_UPDATE_FAILED = 'APP_UPDATE_FAILED';
